Repository leonlolleonlol/DiscordPrototype, pull requests merged in 2025-03, with the labels that each got.

#94 Integrate Message Bar UI into dms-userPortal (#90,#91).
  .gitignore
  communication-platform/client/package-lock.json
  communication-platform/client/package.json
  communication-platform/client/src/lib/utils.js
  communication-platform/client/src/pages/chat/components/chat-container/components/chat-header/index.jsx
  communication-platform/client/src/pages/chat/components/chat-container/components/message-bar/index.jsx
  communication-platform/client/src/pages/chat/components/chat-container/components/message-container/index.jsx
  communication-platform/client/src/pages/chat/components/chat-container/index.jsx
  communication-platform/client/src/pages/chat/components/contacts-container/index.jsx
  communication-platform/client/src/pages/chat/components/empty-chat-container/index.jsx
  communication-platform/client/src/pages/chat/index.jsx
Labels: user story

#95 Create ci.yml
  .github/workflows/ci.yml
Labels: task

#103 Integrate completed DM feature into dev (#6, #10)
  communication-platform/client/package-lock.json
  communication-platform/client/package.json
  communication-platform/client/src/App.jsx
  communication-platform/client/src/lib/store.js
  communication-platform/client/src/pages/auth/auth.js
  communication-platform/client/src/pages/chat/chat.jsx
  communication-platform/client/src/pages/chat/components/chat-container/components/message-bar/index.jsx
  communication-platform/client/src/pages/chat/components/chat-container/components/message-container/index.jsx
  communication-platform/client/src/pages/chat/components/chat-container/index.jsx
  communication-platform/client/src/pages/chat/components/contacts-container/index.jsx
  communication-platform/client/src/pages/chat/index.jsx
  communication-platform/server/controllers/chatRoomControllers.js
  communication-platform/server/controllers/messageController.js
  communication-platform/server/models/chatRoom.js
  communication-platform/server/models/message.js
  communication-platform/server/models/server.js
  communication-platform/server/models/user.js
  communication-platform/server/package-lock.json
  communication-platform/server/package.json
  communication-platform/server/routes/chatRoomRoutes.js
  communication-platform/server/routes/messageRoutes.js
  communication-platform/server/server.js
  communication-platform/shared/package.json
Labels: user story

#114 Implemented sign-out functionality (#112).
  communication-platform/client/src/pages/auth/auth.js
  communication-platform/client/src/pages/chat/components/contacts-container/index.jsx
  communication-platform/server/router.js
Labels: user story

#127 Integrate Chat Room API and Search Feature into dev (#104, #97, #106, #121, #122)
  communication-platform/client/package-lock.json
  communication-platform/client/package.json
  communication-platform/client/src/components/ui/checkbox.jsx
  communication-platform/client/src/lib/apiUtils/chatRoomServices.js
  communication-platform/client/src/lib/apiUtils/messageService.js
  communication-platform/client/src/lib/store.js
  communication-platform/client/src/lib/utils.js
  communication-platform/client/src/pages/chat/chat.jsx
  communication-platform/client/src/pages/chat/components/chat-container/index.jsx
  communication-platform/client/src/pages/chat/components/contacts-container/index.jsx
  communication-platform/server/controllers/chatRoomControllers.js
  communication-platform/server/controllers/messageController.js
  communication-platform/server/models/chatRoom.js
  communication-platform/server/routes/chatRoomRoutes.js
  communication-platform/server/routes/messageRoutes.js
  communication-platform/server/server.js
  communication-platform/shared/package-lock.json
Labels: user story

#131 Integrate Complete Admin Features into dev ( #14, #109, #110, #115, #116)
  communication-platform/client/src/lib/apiUtils/chatRoomServices.js
  communication-platform/client/src/lib/apiUtils/messageService.js
  communication-platform/client/src/lib/store.js
  communication-platform/client/src/pages/auth/index.jsx
  communication-platform/client/src/pages/chat/components/chat-container/components/message-bar/index.jsx
  communication-platform/client/src/pages/chat/components/chat-container/components/message-container/index.jsx
  communication-platform/client/src/pages/chat/components/contacts-container/index.jsx
  communication-platform/server/controllers/chatRoomControllers.js
  communication-platform/server/controllers/messageController.js
  communication-platform/server/router.js
  communication-platform/server/routes/chatRoomRoutes.js
  communication-platform/server/routes/messageRoutes.js
  communication-platform/server/server.js
Labels: epic user story

#141 Integrate ESLint CI Pipeline and Style fixes to dev (#125, #138).
  .github/workflows/ci.yml
  communication-platform/client/README.md
  communication-platform/client/eslint.config.js
  communication-platform/client/package-lock.json
  communication-platform/client/package.json
  communication-platform/client/src/App.jsx
  communication-platform/client/src/lib/apiUtils/chatRoomServices.js
  communication-platform/client/src/lib/apiUtils/messageService.js
  communication-platform/client/src/lib/store.js
  communication-platform/client/src/lib/utils.js
  communication-platform/client/src/main.jsx
  communication-platform/client/src/pages/auth/Auth.jsx
  communication-platform/client/src/pages/auth/auth.js
  communication-platform/client/src/pages/chat/Chat.jsx
  communication-platform/client/src/pages/chat/components/ContactsContainer.jsx
  communication-platform/client/src/pages/chat/components/EmptyChatContainer.jsx
  communication-platform/client/src/pages/chat/components/chat-container/ChatContainer.jsx
  communication-platform/client/src/pages/chat/components/chat-container/components/ChatHeader.jsx
  communication-platform/client/src/pages/chat/components/chat-container/components/MessageBar.jsx
  communication-platform/client/src/pages/chat/components/chat-container/components/MessageContainer.jsx
  communication-platform/client/src/pages/chat/components/chat-container/components/chat-header/index.jsx
  communication-platform/client/src/pages/profile/Profile.jsx
  communication-platform/client/tailwind.config.js
  communication-platform/client/vite.config.js
  communication-platform/server/controllers/chatRoomControllers.js
  communication-platform/server/controllers/messageController.js
  communication-platform/server/eslint.config.js
  communication-platform/server/models/chatRoom.js
  communication-platform/server/models/message.js
  communication-platform/server/models/server.js
  communication-platform/server/models/user.js
  communication-platform/server/package-lock.json
  communication-platform/server/package.json
  communication-platform/server/router.js
  communication-platform/server/routes/chatRoomRoutes.js
  communication-platform/server/routes/messageRoutes.js
  communication-platform/server/security.js
  communication-platform/server/server.js
  communication-platform/shared/package-lock.json
  communication-platform/shared/package.json
  communication-platform/shared/validation.js
Labels: enhancement, user story

#143 Integrate UX Improvements to dev (#142, #129, #130).
  communication-platform/client/src/lib/store.js
  communication-platform/client/src/pages/chat/components/ContactsContainer.jsx
  communication-platform/client/src/pages/chat/components/chat-container/components/MessageContainer.jsx
Labels: bug, enhancement, user story
